[package]
name = "rs-sync"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
sha2 = "0.10.8"
walkdir = "2.5.0"
